# Generated by Django 5.2.17 on 2026-09-03 17:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=120, verbose_name='দোকানের নাম')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('district', models.CharField(blank=True, max_length=40, verbose_name='জেলা')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('banner_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('approved', 'অনুমোদিত'), ('suspended', 'স্থগিত')], default='pending', max_length=12)),
                ('is_verified', models.BooleanField(default=False, verbose_name='যাচাই করা')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='খালি রাখলে ক্যাটাগরির হার প্রযোজ্য হবে।', max_digits=5, verbose_name='কমিশন (%)')),
                ('ships_in_days', models.PositiveSmallIntegerField(default=2, verbose_name='কত দিনে পাঠায়')),
                ('response_rate', models.PositiveSmallIntegerField(default=90, verbose_name='রেসপন্স রেট (%)')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('pickup_address', models.JSONField(blank=True, default=dict)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'দোকান',
                'verbose_name_plural': 'দোকান',
                'ordering': ['-rating_avg', 'shop_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nid_number', models.CharField(blank=True, max_length=25, verbose_name='NID নম্বর')),
                ('nid_front', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('nid_back', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('trade_license', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('bkash_number', models.CharField(blank=True, max_length=14, verbose_name='বিকাশ নম্বর')),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('bank_account_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_number', models.CharField(blank=True, max_length=40)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=250)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC',
            },
        ),
    ]
