# Generated by Django 5.2.17 on 2026-09-03 18:19

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorkyc',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/%Y/%m/', validators=[common.validators.validate_image_file], verbose_name='NID পেছনের দিক'),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/%Y/%m/', validators=[common.validators.validate_image_file], verbose_name='NID সামনের দিক'),
        ),
        migrations.AlterField(
            model_name='vendorkyc',
            name='trade_license',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/%Y/%m/', validators=[common.validators.validate_image_file], verbose_name='ট্রেড লাইসেন্স'),
        ),
    ]
