# Generated by Django 5.2.17 on 2026-09-12 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorkyc_nid_back_alter_vendorkyc_nid_front_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status', '-rating_avg', 'shop_name'], name='vendors_ven_status_dfd566_idx'),
        ),
    ]
