# Generated by Django 5.2.17 on 2026-09-03 17:24

import apps.orders.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('promotions', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=apps.orders.models.make_order_number, max_length=20, unique=True)),
                ('shipping_address', models.JSONField(default=dict)),
                ('payment_method', models.CharField(choices=[('cod', 'ক্যাশ অন ডেলিভারি'), ('bkash', 'বিকাশ'), ('nagad', 'নগদ'), ('card', 'কার্ড / ব্যাংক')], default='cod', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('paid', 'পরিশোধিত'), ('refunded', 'ফেরত'), ('failed', 'ব্যর্থ')], default='pending', max_length=10)),
                ('items_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'অর্ডার',
                'verbose_name_plural': 'অর্ডার',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_number', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('confirmed', 'নিশ্চিত'), ('packed', 'প্যাক হয়েছে'), ('shipped', 'পাঠানো হয়েছে'), ('delivered', 'ডেলিভারি হয়েছে'), ('cancelled', 'বাতিল'), ('returned', 'ফেরত')], default='pending', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('courier', models.CharField(blank=True, max_length=60)),
                ('tracking_code', models.CharField(blank=True, max_length=60)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('settled', models.BooleanField(default=False, help_text='লেজারে এন্ট্রি বসানো হয়েছে কি না')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'পার্সেল (ভেন্ডর অর্ডার)',
                'verbose_name_plural': 'পার্সেল (ভেন্ডর অর্ডার)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=200)),
                ('product_slug', models.SlugField(blank=True, max_length=220)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant')),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.vendororder')),
            ],
            options={
                'verbose_name': 'অর্ডারের পণ্য',
                'verbose_name_plural': 'অর্ডারের পণ্য',
                'ordering': ['id'],
            },
        ),
    ]
