# Generated by Django 5.2.17 on 2026-09-08 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('idempotency_key',), name='uniq_order_idempotency_guest'),
        ),
    ]
