# Generated by Django 5.2.17 on 2026-09-03 17:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('cta', models.CharField(default='দেখুন', max_length=40, verbose_name='বোতামের লেখা')),
                ('href', models.CharField(default='/products', max_length=200, verbose_name='লিংক')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('tone', models.CharField(choices=[('brand', 'সবুজ'), ('dark', 'গাঢ়'), ('accent', 'সোনালি')], default='brand', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ব্যানার',
                'verbose_name_plural': 'ব্যানার',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'ব্র্যান্ড',
                'verbose_name_plural': 'ব্র্যান্ড',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='নাম')),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('icon', models.CharField(blank=True, max_length=8, verbose_name='আইকন (ইমোজি)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'ক্যাটাগরি',
                'verbose_name_plural': 'ক্যাটাগরি',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='নাম')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='স্পেসিফিকেশন')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('pending', 'অনুমোদনের অপেক্ষায়'), ('live', 'সচল'), ('rejected', 'বাতিল')], default='pending', max_length=10)),
                ('free_shipping', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'পণ্য',
                'verbose_name_plural': 'পণ্য',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'পণ্যের ছবি',
                'verbose_name_plural': 'পণ্যের ছবি',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('options', models.JSONField(blank=True, default=dict, help_text='যেমন {"সাইজ": "M", "রঙ": "কালো"}')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'ভ্যারিয়েন্ট',
                'verbose_name_plural': 'ভ্যারিয়েন্ট',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'রিভিউ',
                'verbose_name_plural': 'রিভিউ',
                'ordering': ['-created_at'],
            },
        ),
    ]
