# Generated by Django 5.2.17 on 2026-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('vendors', '0003_vendor_vendors_ven_status_dfd566_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_price_2d2a4c_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-sold_count'], name='catalog_pro_status_56bc62_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'price'], name='catalog_pro_status_30ba48_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-rating_avg'], name='catalog_pro_status_570dc0_idx'),
        ),
    ]
