# Generated by Django 5.2.17 on 2026-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_catalog_pro_price_2d2a4c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='catalog_pro_product_4ee3b8_idx'),
        ),
    ]
