# Generated by Django 5.2.17 on 2026-09-03 17:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='কোড')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='বর্ণনা')),
                ('type', models.CharField(choices=[('flat', 'নির্দিষ্ট টাকা'), ('percent', 'শতাংশ')], default='flat', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মান')),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='সর্বনিম্ন অর্ডার')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='সর্বোচ্চ ছাড়')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'কুপন',
                'verbose_name_plural': 'কুপন',
                'ordering': ['-created_at'],
            },
        ),
    ]
