# Generated by Django 5.2.17 on 2026-09-03 17:24

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=14, unique=True, validators=[apps.accounts.models.validate_bd_phone], verbose_name='মোবাইল')),
                ('full_name', models.CharField(max_length=120, verbose_name='পুরো নাম')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('role', models.CharField(choices=[('customer', 'ক্রেতা'), ('vendor', 'বিক্রেতা'), ('staff', 'স্টাফ')], default='customer', max_length=12)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ইউজার',
                'verbose_name_plural': 'ইউজার',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(max_length=120, verbose_name='প্রাপকের নাম')),
                ('phone', models.CharField(max_length=14, validators=[apps.accounts.models.validate_bd_phone])),
                ('division', models.CharField(max_length=40, verbose_name='বিভাগ')),
                ('district', models.CharField(max_length=40, verbose_name='জেলা')),
                ('thana', models.CharField(max_length=60, verbose_name='থানা/উপজেলা')),
                ('address_line', models.TextField(verbose_name='বিস্তারিত ঠিকানা')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ডেলিভারি নোট')),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ঠিকানা',
                'verbose_name_plural': 'ঠিকানা',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
