# Generated by Django 5.2.17 on 2026-09-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tran_id', models.CharField(max_length=40, unique=True)),
                ('gateway', models.CharField(default='sslcommerz', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'শুরু হয়েছে'), ('success', 'সফল'), ('failed', 'ব্যর্থ'), ('cancelled', 'ক্রেতা বাতিল করেছেন'), ('mismatch', 'অঙ্ক মেলেনি'), ('refunded', 'ফেরত')], db_index=True, default='initiated', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('val_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('card_type', models.CharField(blank=True, max_length=60)),
                ('bank_tran_id', models.CharField(blank=True, max_length=80)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('error_reason', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'পেমেন্ট লেনদেন',
                'verbose_name_plural': 'পেমেন্ট লেনদেন',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx')],
            },
        ),
    ]
