# Generated by Django 5.2.17 on 2026-09-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('requested', 'অনুরোধ করা হয়েছে'), ('processing', 'প্রক্রিয়াধীন'), ('paid', 'পরিশোধিত'), ('failed', 'ব্যর্থ')], default='processing', max_length=12)),
                ('method', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'পে-আউট',
                'verbose_name_plural': 'পে-আউট',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sale', 'বিক্রি'), ('commission', 'কমিশন'), ('refund', 'রিফান্ড'), ('adjustment', 'সমন্বয়')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='vendors.vendor')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.vendororder')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='payouts.payout')),
            ],
            options={
                'verbose_name': 'লেজার এন্ট্রি',
                'verbose_name_plural': 'লেজার এন্ট্রি',
                'ordering': ['-created_at'],
            },
        ),
    ]
